// Dotadle — Hero Database
// Portrait: https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/{id}.png
// Ability:  https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/abilities/{abilityId}.png

const HEROES = [
  // ─────────────────── AGILITY ───────────────────
  { id:"antimage", name:"Anti-Mage", attribute:"Agility", attack:"Melee", roles:["Carry","Escape"], complexity:2, year:2013, gender:"Male",
    lore:"A devout monk who turned against magic after his monastery was slaughtered. He hunts spellcasters across the world.",
    quote:"Magic is an abomination.", abilities:["antimage_mana_break","antimage_blink","antimage_spell_shield","antimage_mana_void"], emojis:["🚫","✨","🥷"] },
  { id:"bloodseeker", name:"Bloodseeker", attribute:"Agility", attack:"Melee", roles:["Carry","Jungler"], complexity:1, year:2013, gender:"Male",
    lore:"A ritual killer of the Flayed Twins who feeds on blood to sustain his murderous crusade.",
    quote:"Your blood... I can smell it.", abilities:["bloodseeker_bloodrage","bloodseeker_blood_bath","bloodseeker_thirst","bloodseeker_rupture"], emojis:["🩸","🔪","👁️"] },
  { id:"bounty_hunter", name:"Bounty Hunter", attribute:"Agility", attack:"Melee", roles:["Carry","Support","Jungler"], complexity:2, year:2013, gender:"Male",
    lore:"A stealthy mercenary who tracks enemies, marks them for gold bounties, and strikes from the shadows.",
    quote:"My prices are fair... The dying is extra.", abilities:["bounty_hunter_shuriken_toss","bounty_hunter_jinada","bounty_hunter_wind_walk","bounty_hunter_track"], emojis:["💰","👁️","🥷"] },
  { id:"broodmother", name:"Broodmother", attribute:"Agility", attack:"Melee", roles:["Carry","Pusher"], complexity:2, year:2013, gender:"Female",
    lore:"An ancient spider goddess who weaves webs across lanes and spawns an endless brood of spiderlings.",
    quote:"My children are endless.", abilities:["broodmother_spawn_spiderlings","broodmother_spin_web","broodmother_silken_bola","broodmother_insatiable_hunger"], emojis:["🕷️","🕸️","🥚"] },
  { id:"clinkz", name:"Clinkz", attribute:"Agility", attack:"Ranged", roles:["Carry","Escape"], complexity:2, year:2013, gender:"Male",
    lore:"A skeletal archer consumed by hellfire, now an undead specter who hunts the living.",
    quote:"Death rides on every arrow.", abilities:["clinkz_strafe","clinkz_tar_bomb","clinkz_wind_walk","clinkz_burning_army"], emojis:["🏹","💀","🔥"] },
  { id:"drow_ranger", name:"Drow Ranger", attribute:"Agility", attack:"Ranged", roles:["Carry","Disabler"], complexity:1, year:2013, gender:"Female",
    lore:"A skilled archer raised by forest spirits who silences enemies with freezing arrows and sheer marksmanship.",
    quote:"I walk alone.", abilities:["drow_ranger_frost_arrows","drow_ranger_gust","drow_ranger_multishot","drow_ranger_marksmanship"], emojis:["🏹","❄️","🌲"] },
  { id:"ember_spirit", name:"Ember Spirit", attribute:"Agility", attack:"Melee", roles:["Carry","Escape"], complexity:3, year:2013, gender:"Male",
    lore:"A fiery elemental spirit bound in mortal form who leaves blazing remnants as he dashes across the battlefield.",
    quote:"Through fire, I am reborn.", abilities:["ember_spirit_searing_chains","ember_spirit_sleight_of_fist","ember_spirit_flame_guard","ember_spirit_fire_remnant"], emojis:["🔥","⚔️","🌀"] },
  { id:"faceless_void", name:"Faceless Void", attribute:"Agility", attack:"Melee", roles:["Carry","Disabler"], complexity:2, year:2013, gender:"Male",
    lore:"A visitor from Clasz who controls time itself, trapping all enemies in a frozen Chronosphere.",
    quote:"Time is my ally.", abilities:["faceless_void_time_walk","faceless_void_time_dilation","faceless_void_time_lock","faceless_void_chronosphere"], emojis:["⏰","🟣","🌀"] },
  { id:"gyrocopter", name:"Gyrocopter", attribute:"Agility", attack:"Ranged", roles:["Carry"], complexity:2, year:2013, gender:"Male",
    lore:"An eccentric inventor who flies into battle in his home-built gyrocopter, raining rockets on enemies.",
    quote:"Up, up, and away!", abilities:["gyrocopter_rocket_barrage","gyrocopter_homing_missile","gyrocopter_flak_cannon","gyrocopter_call_down"], emojis:["🚁","💣","🚀"] },
  { id:"juggernaut", name:"Juggernaut", attribute:"Agility", attack:"Melee", roles:["Carry","Escape"], complexity:1, year:2013, gender:"Male",
    lore:"The last practitioner of the Yurnero blade discipline whose spinning Blade Fury is unstoppable.",
    quote:"None can stop the spinning blade!", abilities:["juggernaut_blade_fury","juggernaut_healing_ward","juggernaut_blade_dance","juggernaut_omni_slash"], emojis:["⚔️","🌀","🎭"] },
  { id:"luna", name:"Luna", attribute:"Agility", attack:"Ranged", roles:["Carry"], complexity:1, year:2013, gender:"Female",
    lore:"A commander of the Knights of the Moon who harnesses the power of Selemene herself.",
    quote:"Selemene's light guides my sword.", abilities:["luna_lucent_beam","luna_moon_glaive","luna_lunar_blessing","luna_eclipse"], emojis:["🌙","🐈","✨"] },
  { id:"medusa", name:"Medusa", attribute:"Agility", attack:"Ranged", roles:["Carry","Durable"], complexity:1, year:2013, gender:"Female",
    lore:"A naga cursed with the form of a Medusa whose stone gaze stops charging armies dead in their tracks.",
    quote:"Don't look into my eyes.", abilities:["medusa_split_shot","medusa_mystic_snake","medusa_mana_shield","medusa_stone_gaze"], emojis:["🐍","👁️","🪨"] },
  { id:"mirana", name:"Mirana", attribute:"Agility", attack:"Ranged", roles:["Carry","Support","Disabler","Escape"], complexity:2, year:2013, gender:"Female",
    lore:"A princess of the Nightsilver Woods who rides a sacred white tigress and fires sacred arrows.",
    quote:"By the grace of Luna!", abilities:["mirana_starstorm","mirana_arrow","mirana_leap","mirana_moonlight_shadow"], emojis:["🌙","🏹","🐅"] },
  { id:"monkey_king", name:"Monkey King", attribute:"Agility", attack:"Melee", roles:["Carry","Escape"], complexity:2, year:2016, gender:"Male",
    lore:"A legendary trickster monkey who wields a magical staff, hides in trees, and clones himself in battle.",
    quote:"The Monkey King is here!", abilities:["monkey_king_boundless_strike","monkey_king_tree_dance","monkey_king_jingu_mastery","monkey_king_wukongs_command"], emojis:["🐒","🌲","👑"] },
  { id:"morphling", name:"Morphling", attribute:"Agility", attack:"Ranged", roles:["Carry","Escape"], complexity:3, year:2013, gender:"Other",
    lore:"An elemental being of pure water who can reshape its entire form and even replicate enemy heroes.",
    quote:"I am all things.", abilities:["morphling_waveform","morphling_adaptive_strike_agi","morphling_morph","morphling_replicate"], emojis:["💧","🌊","🔄"] },
  { id:"naga_siren", name:"Naga Siren", attribute:"Agility", attack:"Melee", roles:["Carry","Support"], complexity:2, year:2013, gender:"Female",
    lore:"A naga warrior who creates mirror images to overwhelm foes and puts all enemies to sleep with her song.",
    quote:"Sleep... and dream of your defeat.", abilities:["naga_siren_mirror_image","naga_siren_ensnare","naga_siren_rip_tide","naga_siren_song_of_the_siren"], emojis:["🧜‍♀️","💤","🎵"] },
  { id:"nyx_assassin", name:"Nyx Assassin", attribute:"Agility", attack:"Melee", roles:["Support","Disabler"], complexity:2, year:2013, gender:"Male",
    lore:"A chosen assassin of the Nyx cult who lurks in burrows and strikes with venomous impaling claws.",
    quote:"Many are Nyx. I am many.", abilities:["nyx_assassin_impale","nyx_assassin_mana_burn","nyx_assassin_spiked_carapace","nyx_assassin_vendetta"], emojis:["🦂","🥷","⚡"] },
  { id:"phantom_assassin", name:"Phantom Assassin", attribute:"Agility", attack:"Melee", roles:["Carry","Escape"], complexity:1, year:2013, gender:"Female",
    lore:"A mysterious killer of the Veiled Sisters whose critical strikes can shatter the mightiest foes in one blow.",
    quote:"Death is certain, its hour is not.", abilities:["phantom_assassin_stifling_dagger","phantom_assassin_phantom_strike","phantom_assassin_blur","phantom_assassin_coup_de_grace"], emojis:["🗡️","💀","🎭"] },
  { id:"phantom_lancer", name:"Phantom Lancer", attribute:"Agility", attack:"Melee", roles:["Carry","Escape"], complexity:2, year:2013, gender:"Male",
    lore:"A spirit warrior who creates an army of phantom copies to overwhelm and confuse his enemies.",
    quote:"You cannot fight what you cannot see.", abilities:["phantom_lancer_spirit_lance","phantom_lancer_doppelwalk","phantom_lancer_phantom_edge","phantom_lancer_juxtapose"], emojis:["👥","🔱","🌀"] },
  { id:"razor", name:"Razor", attribute:"Agility", attack:"Ranged", roles:["Carry","Durable"], complexity:1, year:2013, gender:"Male",
    lore:"The Lightning Revenant who links to his target, stealing their damage and turning it against them.",
    quote:"Shocking, isn't it?", abilities:["razor_plasma_field","razor_static_link","razor_storm_surge","razor_eye_of_the_storm"], emojis:["⚡","🌩️","🔗"] },
  { id:"riki", name:"Riki", attribute:"Agility", attack:"Melee", roles:["Carry","Support","Escape"], complexity:1, year:2013, gender:"Male",
    lore:"A diminutive exile who is permanently invisible, striking from the shadows and vanishing in smoke.",
    quote:"They'll never hear me coming.", abilities:["riki_smoke_screen","riki_blink_strike","riki_tricks_of_the_trade","riki_cloak_and_dagger"], emojis:["🌫️","🗡️","🥷"] },
  { id:"nevermore", name:"Shadow Fiend", attribute:"Agility", attack:"Ranged", roles:["Carry"], complexity:2, year:2013, gender:"Male",
    lore:"A demon who steals the souls of his victims to amplify his deadly Shadowraze barrage.",
    quote:"The Shadow Fiend will feast on your soul.", abilities:["nevermore_shadowraze1","nevermore_necromastery","nevermore_presence_of_the_dark_lord","nevermore_requiem"], emojis:["😈","👻","🔥"] },
  { id:"slark", name:"Slark", attribute:"Agility", attack:"Melee", roles:["Carry","Escape"], complexity:2, year:2013, gender:"Male",
    lore:"A prison escapee who pounces on prey and steals their attributes to grow stronger over time.",
    quote:"Slark will NOT go back to prison!", abilities:["slark_dark_pact","slark_pounce","slark_essence_shift","slark_shadow_dance"], emojis:["🐟","🗡️","🏃"] },
  { id:"sniper", name:"Sniper", attribute:"Agility", attack:"Ranged", roles:["Carry"], complexity:1, year:2013, gender:"Male",
    lore:"A sharpshooter from the mountains of Knollen who assassinates targets at extreme range.",
    quote:"If it bleeds, I can kill it.", abilities:["sniper_shrapnel","sniper_headshot","sniper_aim","sniper_assassinate"], emojis:["🎯","🔫","💥"] },
  { id:"spectre", name:"Spectre", attribute:"Agility", attack:"Melee", roles:["Carry","Durable"], complexity:2, year:2013, gender:"Female",
    lore:"A spectral entity that exists between realities, haunting enemies across any distance with her presence.",
    quote:"Suffering is the coin of this realm.", abilities:["spectre_spectral_dagger","spectre_desolate","spectre_dispersion","spectre_haunt"], emojis:["👻","🗡️","🟣"] },
  { id:"templar_assassin", name:"Templar Assassin", attribute:"Agility", attack:"Ranged", roles:["Carry","Escape"], complexity:2, year:2013, gender:"Female",
    lore:"A silent Templar who cloaks in psi blades and hunts with cold psychic precision.",
    quote:"My thoughts are hidden... as am I.", abilities:["templar_assassin_refraction","templar_assassin_meld","templar_assassin_psi_blades","templar_assassin_psionic_trap"], emojis:["🗡️","🥷","🟣"] },
  { id:"terrorblade", name:"Terrorblade", attribute:"Agility", attack:"Melee", roles:["Carry"], complexity:2, year:2014, gender:"Male",
    lore:"A demon imprisoned in hell for crimes against demonkind who escaped to plague the mortal world.",
    quote:"I am my own demon.", abilities:["terrorblade_reflection","terrorblade_conjure_image","terrorblade_metamorphosis","terrorblade_sunder"], emojis:["😈","👥","🔴"] },
  { id:"troll_warlord", name:"Troll Warlord", attribute:"Agility", attack:"Melee", roles:["Carry","Disabler"], complexity:2, year:2013, gender:"Male",
    lore:"A tribal warlord who switches between melee and ranged and builds unstoppable attack speed.",
    quote:"You won't stand against Jah'rakal!", abilities:["troll_warlord_berserkers_rage","troll_warlord_whirling_axes_ranged","troll_warlord_fervor","troll_warlord_battle_trance"], emojis:["🪓","😠","⚔️"] },
  { id:"ursa", name:"Ursa", attribute:"Agility", attack:"Melee", roles:["Carry","Jungler"], complexity:1, year:2013, gender:"Male",
    lore:"A fearsome bear warrior whose fury stacks into devastating paw strikes that annihilate even Roshan.",
    quote:"Roshan is merely an appetizer.", abilities:["ursa_earthshock","ursa_overpower","ursa_fury_swipes","ursa_enrage"], emojis:["🐻","😤","💪"] },
  { id:"viper", name:"Viper", attribute:"Agility", attack:"Ranged", roles:["Carry","Durable"], complexity:1, year:2013, gender:"Male",
    lore:"A venomous creature that slows and poisons its prey, draining life while corroding their armor.",
    quote:"Your venom is weak compared to mine.", abilities:["viper_poison_attack","viper_nethertoxin","viper_corrosive_skin","viper_viper_strike"], emojis:["🐍","☠️","💚"] },
  { id:"weaver", name:"Weaver", attribute:"Agility", attack:"Ranged", roles:["Carry","Escape"], complexity:2, year:2013, gender:"Male",
    lore:"An ancient insect-like creature that phases in and out of the physical world to evade attacks.",
    quote:"I am the unraveling at the edges of your world.", abilities:["weaver_the_swarm","weaver_shukuchi","weaver_geminate_attack","weaver_time_lapse"], emojis:["🐛","🕸️","⏪"] },
  { id:"arc_warden", name:"Arc Warden", attribute:"Agility", attack:"Ranged", roles:["Carry"], complexity:3, year:2015, gender:"Other",
    lore:"A primordial remnant of the universe's first conflict who guards against the merging of opposing forces.",
    quote:"I am the remnant of a war older than time.", abilities:["arc_warden_flux","arc_warden_magnetic_field","arc_warden_spark_wraith","arc_warden_tempest_double"], emojis:["⚡","🔮","👥"] },

  // ─────────────────── STRENGTH ───────────────────
  { id:"alchemist", name:"Alchemist", attribute:"Strength", attack:"Melee", roles:["Carry","Jungler"], complexity:2, year:2013, gender:"Male",
    lore:"A goblin alchemist and his ogre mount who brew volatile chemicals and farm gold with ruthless efficiency.",
    quote:"Brew it! Bottle it! Sell it!", abilities:["alchemist_acid_spray","alchemist_unstable_concoction","alchemist_corrosive_weaponry","alchemist_chemical_rage"], emojis:["🧪","💰","🔬"] },
  { id:"axe", name:"Axe", attribute:"Strength", attack:"Melee", roles:["Durable","Initiator","Disabler"], complexity:1, year:2013, gender:"Male",
    lore:"A reckless warrior who challenges every foe to one-on-one combat, then executes the weakened.",
    quote:"Axe is not impressed!", abilities:["axe_berserkers_call","axe_battle_hunger","axe_counter_helix","axe_culling_blade"], emojis:["🪓","😤","💪"] },
  { id:"beastmaster", name:"Beastmaster", attribute:"Strength", attack:"Melee", roles:["Initiator","Jungler"], complexity:2, year:2013, gender:"Male",
    lore:"A wild man of the forests who commands hawks and boars and silences enemies with a mighty roar.",
    quote:"Man? Not quite. Beast? Never quite.", abilities:["beastmaster_wild_axes","beastmaster_call_of_the_wild_hawk","beastmaster_inner_beast","beastmaster_primal_roar"], emojis:["🐗","🦅","🌿"] },
  { id:"centaur", name:"Centaur Warrunner", attribute:"Strength", attack:"Melee", roles:["Durable","Initiator"], complexity:1, year:2013, gender:"Male",
    lore:"Champion of the Omexe arena who carries his whole team to safety and stamps enemies into the ground.",
    quote:"Let the battle run red!", abilities:["centaur_hoof_stomp","centaur_double_edge","centaur_return","centaur_stampede"], emojis:["🐴","💪","⚔️"] },
  { id:"chaos_knight", name:"Chaos Knight", attribute:"Strength", attack:"Melee", roles:["Carry","Durable"], complexity:2, year:2013, gender:"Male",
    lore:"A cosmic agent of entropy who rides to sow chaos across the universe with an army of phantom duplicates.",
    quote:"Chaos! Havoc! Ruin!", abilities:["chaos_knight_chaos_bolt","chaos_knight_reality_rift","chaos_knight_chaos_strike","chaos_knight_phantasm"], emojis:["🌌","⚡","🐎"] },
  { id:"dragon_knight", name:"Dragon Knight", attribute:"Strength", attack:"Melee", roles:["Carry","Durable"], complexity:1, year:2013, gender:"Male",
    lore:"A noble knight with dragon blood who transforms into a mighty dragon to devastate his enemies.",
    quote:"For the kingdom!", abilities:["dragon_knight_breathe_fire","dragon_knight_dragon_tail","dragon_knight_dragon_blood","dragon_knight_elder_dragon_form"], emojis:["🐉","⚔️","🛡️"] },
  { id:"earth_spirit", name:"Earth Spirit", attribute:"Strength", attack:"Melee", roles:["Disabler","Initiator","Support"], complexity:3, year:2013, gender:"Male",
    lore:"An ancient elemental who commands magnetized stones to chain, silence, and destroy across the battlefield.",
    quote:"The earth speaks. I obey.", abilities:["earth_spirit_boulder_smash","earth_spirit_rolling_boulder","earth_spirit_geomagnetic_grip","earth_spirit_magnetize"], emojis:["🪨","🌍","🧲"] },
  { id:"earthshaker", name:"Earthshaker", attribute:"Strength", attack:"Melee", roles:["Disabler","Initiator"], complexity:2, year:2013, gender:"Male",
    lore:"A rock-formed centaur who fissures the earth and delivers devastating Echo Slams in teamfights.",
    quote:"The earth... SHAKES!", abilities:["earthshaker_fissure","earthshaker_enchant_totem","earthshaker_aftershock","earthshaker_echo_slam"], emojis:["🌍","💥","🪨"] },
  { id:"elder_titan", name:"Elder Titan", attribute:"Strength", attack:"Melee", roles:["Disabler","Initiator"], complexity:3, year:2013, gender:"Male",
    lore:"The oldest living being who forged the world and now seeks to crack it open with Earth Splitter.",
    quote:"Before there was life, I was.", abilities:["elder_titan_ancestral_spirit","elder_titan_echo_stomp","elder_titan_natural_order","elder_titan_earth_splitter"], emojis:["⚡","🌍","👴"] },
  { id:"huskar", name:"Huskar", attribute:"Strength", attack:"Ranged", roles:["Carry","Durable"], complexity:2, year:2013, gender:"Male",
    lore:"A Sacred Warrior who burns his own life force as fuel, growing deadlier the lower his health drops.",
    quote:"Death is no fate for a warrior.", abilities:["huskar_inner_fire","huskar_burning_spear","huskar_berserkers_blood","huskar_life_break"], emojis:["🔥","💪","❤️"] },
  { id:"io", name:"Io", attribute:"Strength", attack:"Ranged", roles:["Support"], complexity:3, year:2013, gender:"Other",
    lore:"A fundamental wisp-like force of the universe that bonds with allies and relocates them across the map.",
    quote:"...", abilities:["wisp_tether","wisp_spirits","wisp_overcharge","wisp_relocate"], emojis:["✨","🔵","🌌"] },
  { id:"kunkka", name:"Kunkka", attribute:"Strength", attack:"Melee", roles:["Carry","Support","Disabler"], complexity:2, year:2013, gender:"Male",
    lore:"The Admiral of a ghost fleet, cursed to fight a sea-demon for eternity, who summons a spectral ship.",
    quote:"Man the cannons! Set the sails!", abilities:["kunkka_torrent","kunkka_tidebringer","kunkka_x_marks_the_spot","kunkka_ghostship"], emojis:["⚓","⚔️","🌊"] },
  { id:"legion_commander", name:"Legion Commander", attribute:"Strength", attack:"Melee", roles:["Carry","Durable"], complexity:2, year:2013, gender:"Female",
    lore:"A legendary general who grows permanently stronger each time she wins a Duel to the death.",
    quote:"My soldiers know no retreat!", abilities:["legion_commander_overwhelming_odds","legion_commander_press_the_attack","legion_commander_moment_of_courage","legion_commander_duel"], emojis:["⚔️","🏅","👸"] },
  { id:"life_stealer", name:"Lifestealer", attribute:"Strength", attack:"Melee", roles:["Carry","Durable"], complexity:2, year:2013, gender:"Male",
    lore:"A cannibal escapee who devours his enemies for health and can even infest the bodies of allies.",
    quote:"I feast on your life!", abilities:["life_stealer_rage","life_stealer_feast","life_stealer_open_wounds","life_stealer_infest"], emojis:["🍖","😤","💀"] },
  { id:"lycan", name:"Lycan", attribute:"Strength", attack:"Melee", roles:["Carry","Jungler"], complexity:2, year:2013, gender:"Male",
    lore:"A noble who discovered his werewolf bloodline and commands a terrifying pack of wolves.",
    quote:"The wolves of Icewrack follow me.", abilities:["lycan_summon_wolves","lycan_howl","lycan_feral_impulse","lycan_shapeshift"], emojis:["🐺","🌕","🪄"] },
  { id:"magnataur", name:"Magnus", attribute:"Strength", attack:"Melee", roles:["Disabler","Initiator"], complexity:2, year:2013, gender:"Male",
    lore:"A powerful rhino-man who skewers multiple enemies at once and reverses their polarity in teamfights.",
    quote:"By my polearm, you shall fall!", abilities:["magnataur_shockwave","magnataur_empower","magnataur_skewer","magnataur_reverse_polarity"], emojis:["🦏","🌀","💥"] },
  { id:"mars", name:"Mars", attribute:"Strength", attack:"Melee", roles:["Carry","Disabler","Initiator"], complexity:2, year:2019, gender:"Male",
    lore:"The first son of heaven, God of War, who has grown weary of paradise and seeks to remake the world.",
    quote:"War... is my element.", abilities:["mars_spear","mars_gods_rebuke","mars_bulwark","mars_arena_of_blood"], emojis:["🔱","⚔️","🛡️"] },
  { id:"night_stalker", name:"Night Stalker", attribute:"Strength", attack:"Melee", roles:["Carry","Disabler"], complexity:1, year:2013, gender:"Male",
    lore:"A creature of pure darkness who becomes an unstoppable predator when night falls across the land.",
    quote:"The night is my domain!", abilities:["night_stalker_void","night_stalker_crippling_fear","night_stalker_hunter_in_the_night","night_stalker_darkness"], emojis:["🦇","🌙","😨"] },
  { id:"omniknight", name:"Omniknight", attribute:"Strength", attack:"Melee", roles:["Support","Durable"], complexity:1, year:2013, gender:"Male",
    lore:"A holy paladin devoted to Omniscience who heals allies and shields them from all magical harm.",
    quote:"Omniscience is with us!", abilities:["omniknight_purification","omniknight_repel","omniknight_degen_aura","omniknight_guardian_angel"], emojis:["✝️","🛡️","💛"] },
  { id:"phoenix", name:"Phoenix", attribute:"Strength", attack:"Ranged", roles:["Support","Disabler"], complexity:3, year:2014, gender:"Other",
    lore:"A dying star that burns itself to ashes then hatches reborn, launching fire spirits and a supernova.",
    quote:"I will be reborn in fire!", abilities:["phoenix_icarus_dive","phoenix_fire_spirits","phoenix_launch_fire_spirit","phoenix_supernova"], emojis:["🔥","🦅","♻️"] },
  { id:"pudge", name:"Pudge", attribute:"Strength", attack:"Melee", roles:["Disabler","Initiator","Durable"], complexity:2, year:2013, gender:"Male",
    lore:"A freakish butcher who hooks distant enemies across the map and drags them back to be dismembered.",
    quote:"Fresh meat!", abilities:["pudge_meat_hook","pudge_rot","pudge_flesh_heap","pudge_dismember"], emojis:["🪝","🥩","💀"] },
  { id:"sand_king", name:"Sand King", attribute:"Strength", attack:"Melee", roles:["Disabler","Initiator","Jungler"], complexity:2, year:2013, gender:"Male",
    lore:"A scorpion-like creature who burrows through sand and unleashes a ground-shaking Epicenter pulse.",
    quote:"The sands will bury you.", abilities:["sandking_burrowstrike","sandking_sand_storm","sandking_caustic_finale","sandking_epicenter"], emojis:["🦂","🏜️","💥"] },
  { id:"slardar", name:"Slardar", attribute:"Strength", attack:"Melee", roles:["Carry","Durable","Disabler"], complexity:1, year:2013, gender:"Male",
    lore:"A Slithereen Guard from the deep sea who bashes enemies senseless and reveals their weak spots.",
    quote:"You cannot escape the deep!", abilities:["slardar_sprint","slardar_bash","slardar_bash_of_the_deep","slardar_amplify_damage"], emojis:["🦎","🌊","💪"] },
  { id:"spirit_breaker", name:"Spirit Breaker", attribute:"Strength", attack:"Melee", roles:["Carry","Disabler","Initiator"], complexity:1, year:2013, gender:"Male",
    lore:"A planar demon who charges across the map at full sprint to deliver crushing bashes from any range.",
    quote:"Barathrum is unstoppable!", abilities:["spirit_breaker_charge_of_darkness","spirit_breaker_bulldoze","spirit_breaker_greater_bash","spirit_breaker_nether_strike"], emojis:["🌀","💥","🐃"] },
  { id:"sven", name:"Sven", attribute:"Strength", attack:"Melee", roles:["Carry","Durable"], complexity:1, year:2013, gender:"Male",
    lore:"A rogue knight and the bastard son of a Vigil Knight who was exiled but forged himself into a legend.",
    quote:"Rogue Knight... I like the sound of that.", abilities:["sven_storm_bolt","sven_great_cleave","sven_warcry","sven_gods_strength"], emojis:["⚔️","💪","🛡️"] },
  { id:"tidehunter", name:"Tidehunter", attribute:"Strength", attack:"Melee", roles:["Durable","Initiator","Disabler"], complexity:1, year:2013, gender:"Male",
    lore:"A sea lord who endures enormous punishment and unleashes a tentacle Ravage to stun entire armies.",
    quote:"The tide will crush you.", abilities:["tidehunter_gush","tidehunter_kraken_shell","tidehunter_anchor_smash","tidehunter_ravage"], emojis:["🌊","🐙","💥"] },
  { id:"shredder", name:"Timbersaw", attribute:"Strength", attack:"Melee", roles:["Carry","Durable"], complexity:3, year:2013, gender:"Male",
    lore:"A paranoid gnome who built a massive timber-shredding mech to destroy every tree in his path.",
    quote:"The trees! They're EVERYWHERE!", abilities:["shredder_whirling_death","shredder_timber_chain","shredder_reactive_armor","shredder_chakram"], emojis:["🌲","🪚","😱"] },
  { id:"tiny", name:"Tiny", attribute:"Strength", attack:"Melee", roles:["Carry","Disabler","Initiator"], complexity:2, year:2013, gender:"Male",
    lore:"A rock elemental who started as a tiny pebble and grows more massive and powerful with each kill.",
    quote:"Growing... always growing.", abilities:["tiny_avalanche","tiny_toss","tiny_tree_grab","tiny_grow"], emojis:["🪨","📈","💥"] },
  { id:"treant", name:"Treant Protector", attribute:"Strength", attack:"Melee", roles:["Support","Durable"], complexity:2, year:2013, gender:"Male",
    lore:"An ancient tree guardian who watches the forest through Living Armor and binds enemies in Overgrowth.",
    quote:"Nature endures.", abilities:["treant_natures_guise","treant_leech_seed","treant_living_armor","treant_overgrowth"], emojis:["🌳","🌿","👀"] },
  { id:"undying", name:"Undying", attribute:"Strength", attack:"Melee", roles:["Durable","Disabler"], complexity:2, year:2013, gender:"Male",
    lore:"A zombie who steals strength from his enemies and transforms into a towering flesh golem at his peak.",
    quote:"Undying hunger... for flesh.", abilities:["undying_decay","undying_soul_rip","undying_tombstone","undying_flesh_golem"], emojis:["🧟","💀","💪"] },
  { id:"wraith_king", name:"Wraith King", attribute:"Strength", attack:"Melee", roles:["Carry","Durable","Disabler"], complexity:1, year:2013, gender:"Male",
    lore:"A spectral king who refuses to stay dead, reincarnates on the battlefield, and raises skeleton armies.",
    quote:"The dead shall serve.", abilities:["skeleton_king_hellfire_blast","skeleton_king_vampiric_spirit","skeleton_king_mortal_strike","skeleton_king_reincarnation"], emojis:["💀","👑","⚔️"] },
  { id:"primal_beast", name:"Primal Beast", attribute:"Strength", attack:"Melee", roles:["Durable","Initiator","Disabler"], complexity:2, year:2022, gender:"Male",
    lore:"A mindless engine of destruction older than civilization who tramples and pulverizes everything in his path.",
    quote:"CRUSH.", abilities:["primal_beast_onslaught","primal_beast_trample","primal_beast_uproar","primal_beast_pulverize"], emojis:["🦍","💥","🪨"] },

  // ─────────────────── INTELLIGENCE ───────────────────
  { id:"ancient_apparition", name:"Ancient Apparition", attribute:"Intelligence", attack:"Ranged", roles:["Support","Disabler"], complexity:2, year:2013, gender:"Other",
    lore:"A primordial shard of ice who exists at the beginning and end of time, shattering frozen enemies.",
    quote:"Cold... so very cold.", abilities:["ancient_apparition_cold_feet","ancient_apparition_ice_vortex","ancient_apparition_chilling_touch","ancient_apparition_ice_blast"], emojis:["🧊","❄️","🌌"] },
  { id:"bane", name:"Bane", attribute:"Intelligence", attack:"Ranged", roles:["Support","Disabler"], complexity:2, year:2013, gender:"Other",
    lore:"The physical manifestation of nightmares who puts enemies to sleep and channels Fiend's Grip to drain them.",
    quote:"Your nightmares are my reality.", abilities:["bane_enfeeble","bane_brain_sap","bane_nightmare","bane_fiends_grip"], emojis:["😴","😱","🌙"] },
  { id:"crystal_maiden", name:"Crystal Maiden", attribute:"Intelligence", attack:"Ranged", roles:["Support","Disabler"], complexity:1, year:2013, gender:"Female",
    lore:"A frost mage exiled from her homeland who provides global mana regeneration and freezes entire armies.",
    quote:"Crystal clear.", abilities:["crystal_maiden_crystal_nova","crystal_maiden_frostbite","crystal_maiden_brilliance_aura","crystal_maiden_freezing_field"], emojis:["❄️","💙","🔮"] },
  { id:"dark_seer", name:"Dark Seer", attribute:"Intelligence", attack:"Ranged", roles:["Initiator","Disabler"], complexity:3, year:2013, gender:"Male",
    lore:"A brilliant general from another dimension whose Wall of Replica and Vacuum devastates grouped enemies.",
    quote:"Strategy wins wars; strength wins battles.", abilities:["dark_seer_vacuum","dark_seer_ion_shell","dark_seer_surge","dark_seer_wall_of_replica"], emojis:["🌀","🧠","💜"] },
  { id:"dazzle", name:"Dazzle", attribute:"Intelligence", attack:"Ranged", roles:["Support"], complexity:2, year:2013, gender:"Male",
    lore:"A shadow priest of the Nothl Realm who saves allies from death with Shallow Grave and heals with Weave.",
    quote:"The Nothl Realm preserves us all.", abilities:["dazzle_poison_touch","dazzle_shallow_grave","dazzle_shadow_wave","dazzle_weave"], emojis:["💛","🌸","🛡️"] },
  { id:"death_prophet", name:"Death Prophet", attribute:"Intelligence", attack:"Ranged", roles:["Carry","Pusher"], complexity:2, year:2013, gender:"Female",
    lore:"A channeler of spirits who unleashes a devastating Exorcism storm that heals her as it drains enemies.",
    quote:"The spirits of the dead serve me.", abilities:["death_prophet_carrion_swarm","death_prophet_silence","death_prophet_spirit_siphon","death_prophet_exorcism"], emojis:["👻","💜","🌀"] },
  { id:"disruptor", name:"Disruptor", attribute:"Intelligence", attack:"Ranged", roles:["Support","Disabler"], complexity:2, year:2013, gender:"Male",
    lore:"A thunder shaman who uses Kinetic Field and Static Storm to trap and silence entire enemy teams.",
    quote:"Thunder takes what it needs!", abilities:["disruptor_thunder_strike","disruptor_glimpse","disruptor_kinetic_field","disruptor_static_storm"], emojis:["⚡","🌩️","🔮"] },
  { id:"enigma", name:"Enigma", attribute:"Intelligence", attack:"Ranged", roles:["Disabler","Initiator","Jungler"], complexity:3, year:2013, gender:"Other",
    lore:"A cosmic being that is the living embodiment of dark matter who sucks all enemies into a Black Hole.",
    quote:"I am the void between stars.", abilities:["enigma_malefice","enigma_demonic_conversion","enigma_midnight_pulse","enigma_black_hole"], emojis:["🌑","🌌","🕳️"] },
  { id:"grimstroke", name:"Grimstroke", attribute:"Intelligence", attack:"Ranged", roles:["Support","Disabler"], complexity:2, year:2018, gender:"Male",
    lore:"A maddened artist who killed his people with cursed ink now uses that dark art to bind and torment foes.",
    quote:"Art is the ultimate cruelty.", abilities:["grimstroke_stroke_of_fate","grimstroke_phantom_embrace","grimstroke_ink_creature","grimstroke_dark_artistry"], emojis:["🎨","👿","🖋️"] },
  { id:"invoker", name:"Invoker", attribute:"Intelligence", attack:"Ranged", roles:["Carry"], complexity:3, year:2013, gender:"Male",
    lore:"The most powerful mage alive who combines three elemental orbs to invoke over a dozen unique spells.",
    quote:"In my thousands of years, I have learned nothing... then everything.", abilities:["invoker_exort","invoker_wex","invoker_quas","invoker_invoke"], emojis:["🔮","✨","🧙"] },
  { id:"jakiro", name:"Jakiro", attribute:"Intelligence", attack:"Ranged", roles:["Support","Disabler"], complexity:1, year:2013, gender:"Other",
    lore:"A two-headed dragon born of conflicting frost and fire who breathes both in devastating combination.",
    quote:"Two heads, one mind... or is it?", abilities:["jakiro_dual_breath","jakiro_liquid_fire","jakiro_ice_path","jakiro_macropyre"], emojis:["🔥","❄️","🐉"] },
  { id:"keeper_of_the_light", name:"Keeper of the Light", attribute:"Intelligence", attack:"Ranged", roles:["Support"], complexity:3, year:2013, gender:"Male",
    lore:"An ancient horseback scholar who floods allies with mana and blinds enemies with radiant light beams.",
    quote:"The light of all knowledge shines from my lantern.", abilities:["keeper_of_the_light_illuminate","keeper_of_the_light_blinding_light","keeper_of_the_light_chakra_magic","keeper_of_the_light_spirit_form"], emojis:["💡","🐴","✨"] },
  { id:"leshrac", name:"Leshrac", attribute:"Intelligence", attack:"Ranged", roles:["Carry","Pusher"], complexity:2, year:2013, gender:"Male",
    lore:"A nihilistic tormented soul who rains Diabolic Edict and Pulse Nova to annihilate buildings and heroes.",
    quote:"All things must burn.", abilities:["leshrac_split_earth","leshrac_diabolic_edict","leshrac_lightning_storm","leshrac_pulse_nova"], emojis:["💀","⚡","🔥"] },
  { id:"lich", name:"Lich", attribute:"Intelligence", attack:"Ranged", roles:["Support","Disabler"], complexity:1, year:2013, gender:"Male",
    lore:"An undead sorcerer who sacrifices his own creep waves for power and bounces lethal Chain Frost.",
    quote:"The cold never bothers me.", abilities:["lich_frost_nova","lich_frost_shield","lich_sinister_gaze","lich_chain_frost"], emojis:["🧊","💀","🔵"] },
  { id:"lina", name:"Lina", attribute:"Intelligence", attack:"Ranged", roles:["Carry","Support","Disabler"], complexity:2, year:2013, gender:"Female",
    lore:"A fiery sorceress and Crystal Maiden's older sister who scorches enemies with Dragon Slave and Laguna Blade.",
    quote:"Come get burned!", abilities:["lina_dragon_slave","lina_light_strike_array","lina_fiery_soul","lina_laguna_blade"], emojis:["🔥","⚡","👸"] },
  { id:"lion", name:"Lion", attribute:"Intelligence", attack:"Ranged", roles:["Support","Disabler"], complexity:1, year:2013, gender:"Male",
    lore:"A man who sold his soul to a demon, was dragged to hell, but escaped by devouring the demon himself.",
    quote:"My soul was given for power... and I took his too.", abilities:["lion_spike","lion_voodoo","lion_mana_drain","lion_finger_of_death"], emojis:["👉","😈","💀"] },
  { id:"muerta", name:"Muerta", attribute:"Intelligence", attack:"Ranged", roles:["Carry","Support"], complexity:2, year:2023, gender:"Female",
    lore:"The spirit of the dead who wanders seeking the men who killed her beloved, armed with ghostly pistols.",
    quote:"Los muertos never truly die.", abilities:["muerta_dead_shot","muerta_the_calling","muerta_gunslinger","muerta_pierce_the_veil"], emojis:["💀","🌹","🔫"] },
  { id:"furion", name:"Nature's Prophet", attribute:"Intelligence", attack:"Ranged", roles:["Carry","Support","Pusher"], complexity:2, year:2013, gender:"Male",
    lore:"A guardian of the natural world who summons treant armies and teleports anywhere on the map at will.",
    quote:"Nature's call cannot be ignored.", abilities:["furion_sprout","furion_teleportation","furion_force_of_nature","furion_wrath_of_nature"], emojis:["🌳","🌿","⚡"] },
  { id:"necrolyte", name:"Necrophos", attribute:"Intelligence", attack:"Ranged", roles:["Carry","Support"], complexity:2, year:2013, gender:"Male",
    lore:"A plague-bearer whose Heartstopper Aura melts enemy health bars and whose scythe executes the wounded.",
    quote:"Necros is the cure... of life.", abilities:["necrolyte_death_pulse","necrolyte_heartstopper_aura","necrolyte_sadist","necrolyte_reapers_scythe"], emojis:["☠️","🌸","🪖"] },
  { id:"ogre_magi", name:"Ogre Magi", attribute:"Intelligence", attack:"Melee", roles:["Support","Durable"], complexity:1, year:2013, gender:"Male",
    lore:"An unexpectedly magical ogre whose two heads allow him to multicast spells at incredible odds.",
    quote:"Cast spell? Okay!", abilities:["ogre_magi_fireblast","ogre_magi_ignite","ogre_magi_bloodlust","ogre_magi_multicast"], emojis:["🔴","🔥","🎲"] },
  { id:"oracle", name:"Oracle", attribute:"Intelligence", attack:"Ranged", roles:["Support"], complexity:3, year:2015, gender:"Male",
    lore:"A prophet who sees all possible futures and uses this knowledge to save allies and doom enemies.",
    quote:"Every ending has a beginning.", abilities:["oracle_fortunes_end","oracle_fates_edict","oracle_purifying_flames","oracle_false_promise"], emojis:["🔮","👁️","✨"] },
  { id:"obsidian_destroyer", name:"Outworld Destroyer", attribute:"Intelligence", attack:"Ranged", roles:["Carry"], complexity:2, year:2013, gender:"Male",
    lore:"An arcane scholar who imprisons enemies and strips their mana to amplify devastating pure damage.",
    quote:"Your mana is forfeit!", abilities:["obsidian_destroyer_arcane_orb","obsidian_destroyer_astral_imprisonment","obsidian_destroyer_essence_flux","obsidian_destroyer_sanity_eclipse"], emojis:["🔮","💜","⚡"] },
  { id:"puck", name:"Puck", attribute:"Intelligence", attack:"Ranged", roles:["Disabler","Escape"], complexity:3, year:2013, gender:"Other",
    lore:"A playful faerie dragon who phases in and out of reality to confound enemies and trap them in Dream Coil.",
    quote:"Oh the fun we shall have!", abilities:["puck_illusory_orb","puck_waning_rift","puck_phase_shift","puck_dream_coil"], emojis:["🦋","🌀","💜"] },
  { id:"pugna", name:"Pugna", attribute:"Intelligence", attack:"Ranged", roles:["Support","Pusher"], complexity:2, year:2013, gender:"Male",
    lore:"A malevolent nether creature who decrepifies enemies to prevent combat and drains their life force.",
    quote:"Your soul is mine to siphon!", abilities:["pugna_nether_blast","pugna_decrepify","pugna_nether_ward","pugna_life_drain"], emojis:["👻","💛","🌊"] },
  { id:"queenofpain", name:"Queen of Pain", attribute:"Intelligence", attack:"Ranged", roles:["Carry","Disabler","Escape"], complexity:2, year:2013, gender:"Female",
    lore:"A torturess summoned from hell who blinks across the battlefield and delivers a devastating Sonic Wave.",
    quote:"Pain is my gift to you.", abilities:["queenofpain_shadow_strike","queenofpain_blink","queenofpain_scream_of_pain","queenofpain_sonic_wave"], emojis:["😈","💜","⚡"] },
  { id:"rubick", name:"Rubick", attribute:"Intelligence", attack:"Ranged", roles:["Support","Disabler"], complexity:3, year:2013, gender:"Male",
    lore:"The Grand Magus who steals the spells of those he fights, turning enemies' power against them.",
    quote:"A Grand Magus takes what he needs.", abilities:["rubick_telekinesis","rubick_fade_bolt","rubick_arcane_supremacy","rubick_spell_steal"], emojis:["🟢","🔮","🎭"] },
  { id:"shadow_demon", name:"Shadow Demon", attribute:"Intelligence", attack:"Ranged", roles:["Support","Disabler","Escape"], complexity:3, year:2013, gender:"Other",
    lore:"A demon of pure shadow who disrupts enemy minds, creates cursed illusions, and purges corrupted souls.",
    quote:"Your soul... is mine.", abilities:["shadow_demon_disruption","shadow_demon_soul_catcher","shadow_demon_shadow_poison","shadow_demon_demonic_purge"], emojis:["🌑","😈","💜"] },
  { id:"shadow_shaman", name:"Shadow Shaman", attribute:"Intelligence", attack:"Ranged", roles:["Support","Disabler","Pusher"], complexity:1, year:2013, gender:"Male",
    lore:"A voodoo shaman who hexes enemies, binds them in magical Shackles, and summons serpent wards to melt towers.",
    quote:"Rhasta will curse you!", abilities:["shadow_shaman_ether_shock","shadow_shaman_voodoo","shadow_shaman_shackles","shadow_shaman_mass_serpent_ward"], emojis:["🐍","🧿","💚"] },
  { id:"silencer", name:"Silencer", attribute:"Intelligence", attack:"Ranged", roles:["Carry","Support","Disabler"], complexity:2, year:2013, gender:"Male",
    lore:"A blue elf whose curse prevents enemy spellcasting and whose Global Silence shuts down every hero at once.",
    quote:"Silence... is golden.", abilities:["silencer_curse_of_the_silent","silencer_glaives_of_wisdom","silencer_last_word","silencer_global_silence"], emojis:["🤫","💙","📢"] },
  { id:"skywrath_mage", name:"Skywrath Mage", attribute:"Intelligence", attack:"Ranged", roles:["Support","Disabler"], complexity:2, year:2013, gender:"Male",
    lore:"A disgraced skywrath lord whose love was taken by a rival and now rains thunder from above in vengeance.",
    quote:"My wrath shall rain from the skies!", abilities:["skywrath_mage_arcane_bolt","skywrath_mage_concussive_shot","skywrath_mage_ancient_seal","skywrath_mage_mystic_flare"], emojis:["🪶","👑","✨"] },
  { id:"storm_spirit", name:"Storm Spirit", attribute:"Intelligence", attack:"Ranged", roles:["Carry","Escape"], complexity:3, year:2013, gender:"Male",
    lore:"A jovial electrified spirit who zips across the map with Ball Lightning and crackles with electricity.",
    quote:"I'm a little bolt of lightning!", abilities:["storm_spirit_static_remnant","storm_spirit_electric_vortex","storm_spirit_overload","storm_spirit_ball_lightning"], emojis:["🌩️","🐼","🌀"] },
  { id:"tinker", name:"Tinker", attribute:"Intelligence", attack:"Ranged", roles:["Carry","Pusher"], complexity:3, year:2013, gender:"Male",
    lore:"A mechanical genius who Rearms all his items from base and fires missiles at every hero on the map.",
    quote:"And the upgrade is complete!", abilities:["tinker_laser","tinker_heat_seeking_missile","tinker_defense_matrix","tinker_rearm"], emojis:["🤖","🚀","🔧"] },
  { id:"visage", name:"Visage", attribute:"Intelligence", attack:"Ranged", roles:["Support","Durable"], complexity:3, year:2013, gender:"Other",
    lore:"A gargoyle guardian of the dead who commands stone Familiars to stun and claw apart his targets.",
    quote:"None shall pass... to the other side.", abilities:["visage_grave_chill","visage_soul_assumption","visage_graven_image","visage_summon_familiars"], emojis:["🦅","💀","🪨"] },
  { id:"warlock", name:"Warlock", attribute:"Intelligence", attack:"Ranged", roles:["Support","Disabler"], complexity:1, year:2013, gender:"Male",
    lore:"A scholarly summoner who binds his allies with Fatal Bonds and calls forth massive Infernal golems.",
    quote:"The Golem... serves the master.", abilities:["warlock_fatal_bonds","warlock_shadow_word","warlock_upheaval","warlock_rain_of_chaos"], emojis:["🔮","👹","💜"] },
  { id:"winter_wyvern", name:"Winter Wyvern", attribute:"Intelligence", attack:"Ranged", roles:["Support","Disabler"], complexity:2, year:2015, gender:"Female",
    lore:"An ancient dragon mage who freezes the world and forces enemies to attack their own allies with Winter's Curse.",
    quote:"The cold is my companion, my ally, my soul.", abilities:["winter_wyvern_arctic_burn","winter_wyvern_splinter_blast","winter_wyvern_cold_embrace","winter_wyvern_winters_curse"], emojis:["❄️","🐉","🌨️"] },
  { id:"witch_doctor", name:"Witch Doctor", attribute:"Intelligence", attack:"Ranged", roles:["Support","Disabler"], complexity:1, year:2013, gender:"Male",
    lore:"A tribal healer whose paralyzing Cask bounces between enemies and channels a deadly spinning Death Ward.",
    quote:"De witch doctor is in!", abilities:["witch_doctor_paralyzing_cask","witch_doctor_voodoo_restoration","witch_doctor_maledict","witch_doctor_death_ward"], emojis:["🌿","💀","🎵"] },
  { id:"zuus", name:"Zeus", attribute:"Intelligence", attack:"Ranged", roles:["Support"], complexity:1, year:2013, gender:"Male",
    lore:"The lord of heaven who descends to mortal battlefields to remind everyone of his divine power.",
    quote:"Know your place, mortal!", abilities:["zuus_arc_lightning","zuus_lightning_bolt","zuus_heavenly_jump","zuus_thundergods_wrath"], emojis:["⚡","🌩️","👨‍🦳"] },

  // ─────────────────── UNIVERSAL ───────────────────
  { id:"abaddon", name:"Abaddon", attribute:"Universal", attack:"Ranged", roles:["Support","Durable"], complexity:1, year:2013, gender:"Male",
    lore:"A lord blessed by a mystical font who absorbs damage as mana, heals allies, and becomes invulnerable.",
    quote:"The mist of Avernus welcomes you.", abilities:["abaddon_death_coil","abaddon_aphotic_shield","abaddon_frostmourne","abaddon_borrowed_time"], emojis:["☠️","🛡️","🌫️"] },
  { id:"batrider", name:"Batrider", attribute:"Universal", attack:"Ranged", roles:["Disabler","Initiator"], complexity:2, year:2013, gender:"Male",
    lore:"A reckless strygwyr jockey who napalms everything below and lassos enemies around the map.",
    quote:"Look out below!", abilities:["batrider_sticky_napalm","batrider_flamebreak","batrider_firefly","batrider_flaming_lasso"], emojis:["🦇","🔥","🪂"] },
  { id:"brewmaster", name:"Brewmaster", attribute:"Universal", attack:"Melee", roles:["Disabler","Initiator"], complexity:3, year:2013, gender:"Male",
    lore:"A pandaren monk who splits into three powerful elemental spirits: Earth, Storm, and Fire.",
    quote:"Brew. Battle. Breathe.", abilities:["brewmaster_thunder_clap","brewmaster_cinder_brew","brewmaster_drunken_brawler","brewmaster_primal_split"], emojis:["🍺","🐼","🌀"] },
  { id:"chen", name:"Chen", attribute:"Universal", attack:"Ranged", roles:["Support","Jungler"], complexity:3, year:2013, gender:"Male",
    lore:"A holy warrior who converts neutral creeps into his army and heals allies from anywhere on the map.",
    quote:"Your soul belongs to the light!", abilities:["chen_penitence","chen_holy_persuasion","chen_divine_favor","chen_hand_of_god"], emojis:["✝️","🐾","🌿"] },
  { id:"dark_willow", name:"Dark Willow", attribute:"Universal", attack:"Ranged", roles:["Support","Disabler"], complexity:2, year:2017, gender:"Female",
    lore:"A rebellious fairy exile who tangles enemies in briars and terrifies them with the Jex nightmare creature.",
    quote:"Did you just call me a fairy? I am a fiend!", abilities:["dark_willow_bramble_maze","dark_willow_shadow_realm","dark_willow_cursed_crown","dark_willow_terrorize"], emojis:["🌸","😈","🌿"] },
  { id:"dawnbreaker", name:"Dawnbreaker", attribute:"Universal", attack:"Melee", roles:["Support","Durable"], complexity:1, year:2021, gender:"Female",
    lore:"A radiant warrior of Radiance who spins her celestial hammer and flies across the world to save allies.",
    quote:"We fight together, even across the world!", abilities:["dawnbreaker_fire_wraith","dawnbreaker_celestial_hammer","dawnbreaker_luminosity","dawnbreaker_solar_guardian"], emojis:["☀️","⚒️","💫"] },
  { id:"doom_bringer", name:"Doom", attribute:"Universal", attack:"Melee", roles:["Carry","Jungler"], complexity:2, year:2013, gender:"Male",
    lore:"A terrifying demon lord who devours neutral creeps to steal their abilities and silences heroes with Doom.",
    quote:"Doom... upon you.", abilities:["doom_bringer_devour","doom_bringer_scorched_earth","doom_bringer_infernal_blade","doom_bringer_doom"], emojis:["😈","🔥","💀"] },
  { id:"enchantress", name:"Enchantress", attribute:"Universal", attack:"Ranged", roles:["Support","Jungler"], complexity:2, year:2013, gender:"Female",
    lore:"A cheerful enchantress who tames forest creatures and enchants her Impetus javelins with nature's power.",
    quote:"Come on, cheer up! ...Or I'll enchant you.", abilities:["enchantress_impetus","enchantress_enchant","enchantress_nature_attendants","enchantress_untouchable"], emojis:["🌸","🦌","✨"] },
  { id:"hoodwink", name:"Hoodwink", attribute:"Universal", attack:"Ranged", roles:["Support","Disabler","Escape"], complexity:2, year:2020, gender:"Female",
    lore:"A nimble forest squirrel who hides in trees, snares enemies with bushwhack, and fires a lethal rifle shot.",
    quote:"Don't blink, or you'll miss it!", abilities:["hoodwink_acorn_shot","hoodwink_bushwhack","hoodwink_scurry","hoodwink_sharpshooter"], emojis:["🐿️","🌲","🎯"] },
  { id:"lone_druid", name:"Lone Druid", attribute:"Universal", attack:"Ranged", roles:["Carry","Pusher"], complexity:3, year:2013, gender:"Male",
    lore:"A druid elder who transforms into a savage bear and commands a powerful Spirit Bear companion.",
    quote:"In nature, I find strength.", abilities:["lone_druid_spirit_bear","lone_druid_savage_roar","lone_druid_true_form","lone_druid_synergy"], emojis:["🐻","🌲","🔮"] },
  { id:"marci", name:"Marci", attribute:"Universal", attack:"Melee", roles:["Support","Disabler"], complexity:2, year:2021, gender:"Female",
    lore:"A silent but deadly servant of Princess Mirana who throws enemies aside and pulverizes attackers.",
    quote:"...", abilities:["marci_dispose","marci_sidekick","marci_rebound","marci_unleash"], emojis:["💪","🤜","🌸"] },
  { id:"meepo", name:"Meepo", attribute:"Universal", attack:"Melee", roles:["Carry"], complexity:3, year:2013, gender:"Male",
    lore:"A sneaky earth-digging creature who multiplies into five clones, all sharing the same fate.",
    quote:"More and more of me!", abilities:["meepo_earthbind","meepo_poof","meepo_ransack","meepo_divided_we_stand"], emojis:["👥","⛏️","🐀"] },
  { id:"muerta", name:"Muerta", attribute:"Intelligence", attack:"Ranged", roles:["Carry","Support"], complexity:2, year:2023, gender:"Female",
    lore:"The spirit of the dead who wanders seeking the men who killed her beloved, armed with ghostly pistols.",
    quote:"Los muertos never truly die.", abilities:["muerta_dead_shot","muerta_the_calling","muerta_gunslinger","muerta_pierce_the_veil"], emojis:["💀","🌹","🔫"] },
  { id:"pangolier", name:"Pangolier", attribute:"Universal", attack:"Melee", roles:["Carry","Disabler","Escape"], complexity:2, year:2017, gender:"Male",
    lore:"A swashbuckling pangolin duelist who deflects attacks and rolls across the battlefield like a wrecking ball.",
    quote:"En garde! ...Hm, actually garde yourself.", abilities:["pangolier_swashbuckle","pangolier_shield_crash","pangolier_lucky_shot","pangolier_rolling_thunder"], emojis:["🦔","⚔️","🌀"] },
  { id:"snapfire", name:"Snapfire", attribute:"Universal", attack:"Ranged", roles:["Support"], complexity:2, year:2019, gender:"Female",
    lore:"A grandmotherly dragon rider who spoils allies with cookies and fires a massive mortar at enemies.",
    quote:"Mortimer, say hello to the bad men!", abilities:["snapfire_scatterblast","snapfire_firesnap_cookie","snapfire_lil_shredder","snapfire_mortimer_kisses"], emojis:["🔥","🐉","👵"] },
  { id:"techies", name:"Techies", attribute:"Universal", attack:"Ranged", roles:["Disabler"], complexity:3, year:2014, gender:"Male",
    lore:"Manic goblin brothers who plant hidden mines everywhere and detonate them in absolute explosive chaos.",
    quote:"Let's blow stuff up!", abilities:["techies_sticky_bomb","techies_minefield_sign","techies_reactive_tazer","techies_land_mines"], emojis:["💣","💥","😈"] },
  { id:"venomancer", name:"Venomancer", attribute:"Universal", attack:"Ranged", roles:["Support","Pusher","Disabler"], complexity:1, year:2013, gender:"Other",
    lore:"A half-man, half-lizard who saturates the battlefield with venom wards and toxic poison clouds.",
    quote:"Sssssss... the poison takes hold.", abilities:["venomancer_venomous_gale","venomancer_poison_sting","venomancer_plague_ward","venomancer_poison_nova"], emojis:["☠️","💚","🐍"] },
  { id:"void_spirit", name:"Void Spirit", attribute:"Universal", attack:"Melee", roles:["Carry","Escape"], complexity:3, year:2019, gender:"Male",
    lore:"The fifth brother of the spirit elements who phases through reality and tears at enemies with a resonant scythe.",
    quote:"Between moments, I exist.", abilities:["void_spirit_aether_remnant","void_spirit_dissimilate","void_spirit_resonant_pulse","void_spirit_astral_step"], emojis:["🌑","⚡","🌀"] },
  { id:"windrunner", name:"Windranger", attribute:"Universal", attack:"Ranged", roles:["Carry","Support","Disabler","Escape"], complexity:2, year:2013, gender:"Female",
    lore:"A swift archer blessed by the wind who snares enemies with arrows and focuses fire in a rapid burst.",
    quote:"The wind calls to me.", abilities:["windrunner_shackleshot","windrunner_powershot","windrunner_windrun","windrunner_focusfire"], emojis:["🏹","💨","🟠"] },
  { id:"ringmaster", name:"Ringmaster", attribute:"Universal", attack:"Ranged", roles:["Support","Disabler"], complexity:2, year:2024, gender:"Male",
    lore:"A mysterious circus master who entraps enemies in trunks, hypnotizes them, and pelts them with knives.",
    quote:"Step right up... to your doom!", abilities:["ringmaster_tame_the_beasts","ringmaster_hat_trick","ringmaster_impalement","ringmaster_curtain_call"], emojis:["🎩","🎪","🔪"] },
];

// Remove duplicate muerta entry
const seen = new Set();
const HEROES_UNIQUE = HEROES.filter(h => {
  if (seen.has(h.id)) return false;
  seen.add(h.id);
  return true;
});

// Export
if (typeof module !== 'undefined') module.exports = HEROES_UNIQUE;
